spring:
  application:
    name: web-admin
  main:
    allow-bean-definition-overriding: true

server:
  port: 8902
  servlet:
    context-path: /adminApi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/