spring:
  application:
    name: service-message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_community_service?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"

server:
  port: 8805

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/