spring:
  application:
    name: web-user
  main:
    allow-bean-definition-overriding: true

server:
  port: 8901
  servlet:
    context-path: /userApi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/